# Generated by Django 3.1.4 on 2020-12-12 18:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Topicname', models.CharField(help_text='Topic of the Subject', max_length=100)),
                ('Subjname', models.CharField(help_text='Name of the Subject', max_length=100)),
                ('Authname', models.CharField(help_text='Author of the Subject', max_length=100)),
                ('image', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])])),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subjname', models.CharField(help_text='Name of the Subject', max_length=100)),
                ('Authname', models.CharField(help_text='Author of the Subject', max_length=100)),
                ('Authbranch', models.CharField(help_text='Branch of the author', max_length=100)),
                ('file', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docs', 'doc', 'docx', 'txt', 'djvu', 'epub', 'chm'])])),
                ('notes_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iet.subject')),
            ],
        ),
    ]
